apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-source.yaml
  - postgres-target.yaml
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - setup-replication-job.yaml
  - test-replication.yaml

namespace: database-replication
