apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-source
  labels:
    app: postgres-source
spec:
  serviceName: postgres-source
  replicas: 1
  selector:
    matchLabels:
      app: postgres-source
  template:
    metadata:
      labels:
        app: postgres-source
    spec:
      containers:
      - name: postgres
        image: postgres:14
        args:
        - postgres
        - -c
        - wal_level=logical
        - -c
        - max_replication_slots=4
        - -c
        - max_wal_senders=4
        - -c
        - max_logical_replication_workers=4
        - -c
        - log_statement=all
        - -c
        - log_replication_commands=on
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: source.db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - name: postgres-source-data
          mountPath: /var/lib/postgresql/data
        - name: init-source-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-source-script
        configMap:
          name: postgres-config
          items:
          - key: init-source.sql
            path: init-source.sql
  volumeClaimTemplates:
  - metadata:
      name: postgres-source-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-source
spec:
  selector:
    app: postgres-source
  ports:
  - port: 5432
    targetPort: 5432
