apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  source.db: sourcedb
  target.db: targetdb
  init-source.sql: |
    -- Initialize source database (PostgreSQL 14)
    
    -- Create a sample table with test data
    CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE TABLE orders (
        id SERIAL PRIMARY KEY,
        user_id INTEGER REFERENCES users(id),
        product_name VARCHAR(200) NOT NULL,
        amount DECIMAL(10,2) NOT NULL,
        order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Insert sample data
    INSERT INTO users (name, email) VALUES 
        ('John Doe', 'john.doe@example.com'),
        ('Jane Smith', 'jane.smith@example.com'),
        ('Bob Johnson', 'bob.johnson@example.com'),
        ('Alice Brown', 'alice.brown@example.com'),
        ('Charlie Wilson', 'charlie.wilson@example.com');
    
    INSERT INTO orders (user_id, product_name, amount) VALUES 
        (1, 'Laptop', 999.99),
        (2, 'Mouse', 29.99),
        (1, 'Keyboard', 79.99),
        (3, 'Monitor', 299.99),
        (4, 'Headphones', 149.99),
        (5, 'Webcam', 89.99);
    
  init-target.sql: |
    -- Initialize target database (PostgreSQL 16)
    
    -- Create the same schema as source database
    CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE TABLE orders (
        id SERIAL PRIMARY KEY,
        user_id INTEGER REFERENCES users(id),
        product_name VARCHAR(200) NOT NULL,
        amount DECIMAL(10,2) NOT NULL,
        order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
  setup-replication.sql: |
    -- Setup script for logical replication
    -- Run this on the SOURCE database (PostgreSQL 14)
    
    -- Create publication for all tables
    CREATE PUBLICATION my_publication FOR ALL TABLES;
    
    -- Verify publication was created
    SELECT * FROM pg_publication;
    
    -- Show current replication slots (should be empty initially)
    SELECT * FROM pg_replication_slots;
    
  setup-subscription.sql: |
    -- Setup script for subscription
    -- Run this on the TARGET database (PostgreSQL 16)
    
    -- Create subscription to replicate from source
    CREATE SUBSCRIPTION my_subscription
        CONNECTION 'host=postgres-source port=5432 dbname=sourcedb user=postgres password=postgres'
        PUBLICATION my_publication
        WITH (copy_data = true, create_slot = true);
